// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/vhdirk/gir-files.git)
// from webkit2gtk-gir-files
// DO NOT EDIT

mod class;
pub use self::class::Class;

mod context;
pub use self::context::ContextBuilder;
pub use self::context::{Context, NONE_CONTEXT};

mod exception;
pub use self::exception::{Exception, NONE_EXCEPTION};

mod value;
pub use self::value::ValueBuilder;
pub use self::value::{Value, NONE_VALUE};

mod virtual_machine;
pub use self::virtual_machine::{VirtualMachine, NONE_VIRTUAL_MACHINE};

mod weak_value;
pub use self::weak_value::WeakValueBuilder;
pub use self::weak_value::{WeakValue, NONE_WEAK_VALUE};

mod enums;
pub use self::enums::CheckSyntaxMode;
pub use self::enums::CheckSyntaxResult;
pub use self::enums::OptionType;

mod flags;
pub use self::flags::ValuePropertyFlags;

#[doc(hidden)]
pub mod traits {
    pub use super::context::ContextExt;
    pub use super::exception::ExceptionExt;
    pub use super::value::ValueExt;
    pub use super::weak_value::WeakValueExt;
}
