[build-dependencies]
pkg-config = "0.3.7"
system-deps = "6"

[dependencies]
libc = "0.2"
bitflags = "^1.0"

[dependencies.gio]
package = "gio-sys"
version = "0.18"

[dependencies.glib]
package = "glib-sys"
version = "0.18"

[dependencies.gobject]
package = "gobject-sys"
version = "0.18"

[dependencies.gtk]
package = "gtk-sys"
version = "0.18"

[dependencies.soup]
package = "soup3-sys"
version = "0.5"

[dependencies.java_script_core]
package = "javascriptcore4-rs-sys"
path = "../../javascriptcore/sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v2_6 = []
v2_8 = ["v2_6"]
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]
v2_18 = ["v2_16"]
v2_20 = ["v2_18"]
v2_22 = ["v2_20"]
v2_24 = ["v2_22"]
v2_26 = ["v2_22"]
v2_28 = ["v2_26"]
v2_30 = ["v2_28"]
v2_32 = ["v2_30"]
v2_34 = ["v2_32"]
v2_40 = ["v2_28"]

[lib]
name = "webkit2gtk_webextension_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
links = "webkit2gtk4_webextension"
name = "webkit2gtk4-webextension-sys"
version = "0.5.0"
edition = "2021"

[package.metadata.docs.rs]
features = []
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[package.metadata.system-deps.webkit2gtk_web_extension_4_1]
name = "webkit2gtk-web-extension-4.1"
version = "2.4"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_6]
version = "2.6"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_8]
version = "2.8"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_10]
version = "2.10"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_12]
version = "2.12"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_14]
version = "2.14"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_16]
version = "2.16"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_18]
version = "2.18"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_20]
version = "2.20"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_22]
version = "2.22"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_26]
version = "2.26"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_28]
version = "2.28"

[package.metadata.system-deps.webkit2gtk_web_extension_4_1.v2_40]
version = "2.40"
