// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// from webkit2gtk-gir-files
// DO NOT EDIT
#![allow(deprecated)]

#[cfg(feature = "v2_18")]
#[cfg_attr(docsrs, doc(cfg(feature = "v2_18")))]
use crate::DOMClientRect;
use crate::DOMObject;
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::{boxed::Box as Box_, fmt, mem::transmute};

glib::wrapper! {
    #[doc(alias = "WebKitDOMClientRectList")]
    pub struct DOMClientRectList(Object<ffi::WebKitDOMClientRectList, ffi::WebKitDOMClientRectListClass>) @extends DOMObject;

    match fn {
        type_ => || ffi::webkit_dom_client_rect_list_get_type(),
    }
}

impl DOMClientRectList {
    pub const NONE: Option<&'static DOMClientRectList> = None;
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::DOMClientRectList>> Sealed for T {}
}

pub trait DOMClientRectListExt: IsA<DOMClientRectList> + sealed::Sealed + 'static {
    #[cfg_attr(feature = "v2_22", deprecated = "Since 2.22")]
    #[cfg(feature = "v2_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v2_18")))]
    #[allow(deprecated)]
    #[doc(alias = "webkit_dom_client_rect_list_get_length")]
    #[doc(alias = "get_length")]
    fn length(&self) -> libc::c_ulong {
        unsafe { ffi::webkit_dom_client_rect_list_get_length(self.as_ref().to_glib_none().0) }
    }

    #[cfg_attr(feature = "v2_22", deprecated = "Since 2.22")]
    #[cfg(feature = "v2_18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v2_18")))]
    #[allow(deprecated)]
    #[doc(alias = "webkit_dom_client_rect_list_item")]
    fn item(&self, index: libc::c_ulong) -> Option<DOMClientRect> {
        unsafe {
            from_glib_full(ffi::webkit_dom_client_rect_list_item(
                self.as_ref().to_glib_none().0,
                index,
            ))
        }
    }

    fn get_property_length(&self) -> libc::c_ulong {
        ObjectExt::property(self.as_ref(), "length")
    }

    #[doc(alias = "length")]
    fn connect_length_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_length_trampoline<
            P: IsA<DOMClientRectList>,
            F: Fn(&P) + 'static,
        >(
            this: *mut ffi::WebKitDOMClientRectList,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(DOMClientRectList::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::length\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_length_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl<O: IsA<DOMClientRectList>> DOMClientRectListExt for O {}

impl fmt::Display for DOMClientRectList {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("DOMClientRectList")
    }
}
